/**
 * Replay every captured cursor-agent NDJSON fixture through `parseNdjson`
 * → `mapCursorEvent` and compare the produced GSD event stream + final
 * `AssistantMessage` against a snapshot.
 *
 * The replay is fully deterministic given a fixed input NDJSON file — the
 * source of non-determinism is only the capture step. To re-seed the
 * `.expected.json` snapshots after recapturing a fixture, run:
 *
 *   UPDATE_FIXTURE_SNAPSHOTS=1 node --experimental-strip-types \
 *     --test src/resources/extensions/cursor-cli/tests/fixture-replay.test.ts
 *
 * Then re-run without the env var to confirm byte-for-byte stability.
 */

import { describe, test } from "node:test";
import assert from "node:assert/strict";
import {
	readFileSync,
	readdirSync,
	writeFileSync,
	existsSync,
} from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { Readable } from "node:stream";
import type { AssistantMessage, AssistantMessageEvent } from "@gsd/pi-ai";
import { parseNdjson } from "../ndjson-parser.ts";
import { mapCursorEvent } from "../stream-translation.ts";

const HERE = dirname(fileURLToPath(import.meta.url));
const FIXTURES_DIR = join(HERE, "fixtures");

/**
 * Resolve the source-tree path for `target` even when the test runs from
 * `dist-test/`. We discover the location by stripping the `dist-test/`
 * segment from the compiled path. Returns the source path if the
 * translation succeeds, otherwise the original target.
 *
 * Snapshots must always be written to source so they can be committed —
 * `dist-test/` is regenerated by `npm run test:compile`.
 */
function toSourcePath(target: string): string {
	const marker = `${"dist-test"}${"/"}`;
	const idx = target.indexOf(marker);
	if (idx === -1) return target;
	return target.slice(0, idx) + target.slice(idx + marker.length);
}

interface ScrubbedEvent {
	type: string;
	contentIndex?: number;
	delta?: string;
	content?: string;
	toolCall?: {
		type: "toolCall";
		id: string;
		name: string;
		arguments: Record<string, unknown>;
	};
	malformedArguments?: boolean;
	reason?: string;
}

interface ScrubbedMessage {
	role: "assistant";
	content: AssistantMessage["content"];
	api: string;
	provider: string;
	model: string;
	usage: AssistantMessage["usage"];
	stopReason: AssistantMessage["stopReason"];
	errorMessage?: string;
}

interface SnapshotShape {
	model: string;
	events: ScrubbedEvent[];
	final: ScrubbedMessage | null;
}

/**
 * Strip non-deterministic + cyclic fields from a GSD event so the snapshot
 * compares only the intrinsic event payload. In particular we drop the
 * `partial` field — every event in a stream carries a reference to the
 * same growing `AssistantMessage`, which makes the JSON pointlessly large
 * and recursive.
 */
function scrubEvent(event: AssistantMessageEvent): ScrubbedEvent {
	switch (event.type) {
		case "start":
			return { type: "start" };
		case "text_start":
			return { type: "text_start", contentIndex: event.contentIndex };
		case "text_delta":
			return {
				type: "text_delta",
				contentIndex: event.contentIndex,
				delta: event.delta,
			};
		case "text_end":
			return {
				type: "text_end",
				contentIndex: event.contentIndex,
				content: event.content,
			};
		case "thinking_start":
			return { type: "thinking_start", contentIndex: event.contentIndex };
		case "thinking_delta":
			return {
				type: "thinking_delta",
				contentIndex: event.contentIndex,
				delta: event.delta,
			};
		case "thinking_end":
			return {
				type: "thinking_end",
				contentIndex: event.contentIndex,
				content: event.content,
			};
		case "toolcall_start":
			return { type: "toolcall_start", contentIndex: event.contentIndex };
		case "toolcall_delta":
			return {
				type: "toolcall_delta",
				contentIndex: event.contentIndex,
				delta: event.delta,
			};
		case "toolcall_end":
			return {
				type: "toolcall_end",
				contentIndex: event.contentIndex,
				toolCall: {
					type: "toolCall",
					id: event.toolCall.id,
					name: event.toolCall.name,
					arguments: event.toolCall.arguments ?? {},
				},
				...(event.malformedArguments ? { malformedArguments: true } : {}),
			};
		case "server_tool_use":
			return { type: "server_tool_use", contentIndex: event.contentIndex };
		case "web_search_result":
			return { type: "web_search_result", contentIndex: event.contentIndex };
		case "done":
		case "error":
			// Terminal events are surfaced separately via `final`.
			return { type: event.type, reason: event.reason };
	}
}

function scrubMessage(message: AssistantMessage | null | undefined): ScrubbedMessage | null {
	if (!message) return null;
	const scrubbed: ScrubbedMessage = {
		role: "assistant",
		content: message.content,
		api: message.api,
		provider: message.provider,
		model: message.model,
		usage: message.usage,
		stopReason: message.stopReason,
	};
	if (message.errorMessage) scrubbed.errorMessage = message.errorMessage;
	return scrubbed;
}

interface StreamState {
	model: string;
	builder: null;
	sessionId: string | null;
	lastTextContent: string;
	intermediateToolBlocks: AssistantMessage["content"];
	toolResultsById: Map<string, unknown>;
}

function makeFreshState(model: string): StreamState {
	return {
		model,
		builder: null,
		sessionId: null,
		lastTextContent: "",
		intermediateToolBlocks: [],
		toolResultsById: new Map(),
	};
}

async function replayFixture(ndjsonPath: string, model: string): Promise<{
	events: ScrubbedEvent[];
	final: ScrubbedMessage | null;
}> {
	const raw = readFileSync(ndjsonPath, "utf8");
	const stream = Readable.from([raw]);
	const state = makeFreshState(model);
	const events: ScrubbedEvent[] = [];
	let final: ScrubbedMessage | null = null;

	for await (const event of parseNdjson(stream)) {
		const result = mapCursorEvent(
			event,
			state as unknown as Parameters<typeof mapCursorEvent>[1],
		);
		for (const e of result.events) events.push(scrubEvent(e));
		if (result.final) {
			final = scrubMessage(result.final.message);
			break;
		}
	}

	return { events, final };
}

function readMetaModel(fixtureFile: string): string {
	const metaPath = fixtureFile.replace(/\.ndjson$/, ".meta.json");
	if (!existsSync(metaPath)) return "composer-2";
	try {
		const meta = JSON.parse(readFileSync(metaPath, "utf8")) as { model?: string };
		return meta.model ?? "composer-2";
	} catch {
		return "composer-2";
	}
}

describe("fixture replay", () => {
	if (!existsSync(FIXTURES_DIR)) {
		test.skip("fixtures directory not found", () => undefined);
		return;
	}

	const fixtures = readdirSync(FIXTURES_DIR)
		.filter((f) => f.endsWith(".ndjson") && !f.startsWith("."))
		.sort();

	if (fixtures.length === 0) {
		test.skip("no .ndjson fixtures captured yet — run capture.sh", () => undefined);
		return;
	}

	for (const fixture of fixtures) {
		test(`replay ${fixture}`, async () => {
			const ndjsonPath = join(FIXTURES_DIR, fixture);
			const expectedPath = ndjsonPath.replace(/\.ndjson$/, ".expected.json");
			const model = readMetaModel(ndjsonPath);

			const { events, final } = await replayFixture(ndjsonPath, model);
			const snapshot: SnapshotShape = { model, events, final };

			if (process.env.UPDATE_FIXTURE_SNAPSHOTS) {
				const writePath = toSourcePath(expectedPath);
				writeFileSync(writePath, JSON.stringify(snapshot, null, 2) + "\n");
				return;
			}

			if (!existsSync(expectedPath)) {
				assert.fail(
					`missing ${expectedPath} — re-seed with UPDATE_FIXTURE_SNAPSHOTS=1`,
				);
			}

			const expected = JSON.parse(readFileSync(expectedPath, "utf8")) as SnapshotShape;
			assert.deepEqual(snapshot.events, expected.events, "event sequence drifted");
			assert.deepEqual(snapshot.final, expected.final, "final assistant message drifted");
		});
	}
});
